-- Auto-generated by _tmp_asset_pipeline.php on 2026-04-16 05:18:49
-- Clears and re-seeds sh_global_assets with processed assets

TRUNCATE TABLE sh_global_assets;

INSERT INTO sh_global_assets (tenant_id, ascii_key, category, sub_type, filename, width, height, has_alpha, filesize_bytes, z_order, target_px, is_active) VALUES
;